### ISSUE TITLE
more errors are shown when --ignore is used

### ISSUE THREAD

**Issue by Unode** [jcrocholl/pep8#375]
pep8: 1.5.7 on Linux

Sample file (test.py):

    a = {
        "foo": "bar",
        }

If I run `pep8 test.py --ignore=E501` I get:

    ./test.py:3:5: E123 closing bracket does not match indentation of opening bracket's line

however if I run `pep8 test.py` without ignoring anything I get no output.

Is this expected?

**Comment by sigmavirus24** [comment]
I'm fairly confident that it is. You're overwriting the default list of ignored error/warning codes.

**Comment by IanLee1521** [comment]
@Unode -- Yes, this is expected. Unfortunately, in 1.5.7 the DEFAULT_IGNORE list was hidden in the code and not very user facing. Coming in 1.6 I've moved the list to be displayed in the pep8 help information.  Currently:

``` bash
pep8 --help
...
  --ignore=errors      skip errors and warnings (e.g. E4,W) (default:
                       E121,E123,E126,E226,E24,E704)
...
```

**Comment by Unode** [comment]
Thanks, that clarifies it.
