### ISSUE TITLE
Exception thrown in latest pypi version of pep8 (within flake8)

### ISSUE THREAD

**Issue by zachmullen** [jcrocholl/pep8#377]
```
9: Traceback (most recent call last):
9:   File "/usr/local/bin/flake8", line 11, in <module>
9:     sys.exit(main())
9:   File "/usr/local/lib/python2.7/site-packages/flake8/main.py", line 24, in main
9:     flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
9:   File "/usr/local/lib/python2.7/site-packages/flake8/engine.py", line 109, in get_style_guide
9:     styleguide = StyleGuide(**kwargs)
9:   File "/usr/local/lib/python2.7/site-packages/pep8.py", line 1744, in __init__
9:     options, self.paths = process_options(arglist, parse_argv, parser)
9:   File "/usr/local/lib/python2.7/site-packages/pep8.py", line 2024, in process_options
9:     options = read_config(options, args, arglist, parser)
9:   File "/usr/local/lib/python2.7/site-packages/pep8.py", line 1983, in read_config
9:     value = normalize_paths(value, local_dir)
9: UnboundLocalError: local variable 'local_dir' referenced before assignment
```

**Comment by zachmullen** [comment]
pep8 @ 1.6.0, flake8 @ 2.3.0

**Comment by zachmullen** [comment]
The error goes away when I remove the "exclude" value from my config file, which was:

    exclude: girder/external/*

**Comment by IanLee1521** [comment]
Fixed in 6086f61. Thanks!

**Comment by zachmullen** [comment]
Thanks @IanLee1521 !

**Comment by zachmullen** [comment]
Hi @IanLee1521 are you planning to do a point release for this soon, or should I peg my project to 1.5.7 for now?

**Comment by IanLee1521** [comment]
As this is a more critical bug, I'll do a point release by the end of the weekend. Just want to see if any other issues come in as well.

**Comment by zachmullen** [comment]
Awesome, thank you.

**Comment by pedrobaeza** [comment]
I'm going to freeze for now our Travis checks with previous version. Please notify us when this new version is available. Thanks.

**Comment by IanLee1521** [comment]
@zachmullen / @pedrobaeza -- I just pushed version 1.6.1 which fixes this issue. Let me know if you find any other issues.

**Comment by zachmullen** [comment]
Works for me now, thanks for the quick turnaround.

**Comment by pedrobaeza** [comment]
Hi, @IanLee1521, thank you very much for the quick fix. Our CI system is working properly again.
