### ISSUE TITLE
Couldn't mute E731 errors via noqa

### ISSUE THREAD

**Issue by playpauseandstop** [jcrocholl/pep8#379]
I'm not sure that this is proper place, but will try.

Updating to 1.6.1 introduces new E731 errors for "do not assign a lambda expression, use a def" and results that ``flake8`` (as well as ``pep8``) check failed in several places.

As failed code belongs to other dev, I've tried to mute those errors by adding ``# noqa`` comments to end of failed lines, but nothing happened.

So is there any way to mute E731 errors?

**Comment by playpauseandstop** [comment]
And yeah, I can exclude **all** E731 errors by ignoring them as command-line arg or setup.cfg directive, but I don't want to do this, I just want to mute **some** error lines in code

**Comment by sigmavirus24** [comment]
This is one of the stronger recommendations in PEP-0008 that was only recently added to the tool. If you're going to modify those files anyway to add `# noqa` you may as well just fix them. Adding support for `# noqa` to every error code is pointless. You can also pin to an older version of pep8 or exclude those files.

**Comment by playpauseandstop** [comment]
Thanks for explanation, closing this as invalid

**Comment by miki725** [comment]
what about things like:

```python
_ = lambda x: x
```

which is a very common pattern in Django when translations are not ready and so using `gettext` is undesirable but code should be translation-ready since later on you can simply change imports to make it translatable:

```python
from django.utils.translation import ugettext as _
```

in such a case I think it makes sense to enforce `E731` in the rest of the file but allow to apply `noqa` only in specific scenarios

**Comment by sigmavirus24** [comment]
So you write,

```py
_ = lambda x: x
```

In every file you need it in? That seems like an anti-pattern more than a pattern. Why wouldn't you have some module where, while translations are not read, you do:

```py
def ugettext(text):
    return text
```

And then do

```py
from my_app.fake_mod import ugettext as _
```

Then you can very simply rewrite imports with a search for `my_app.fake_mod` to replace with `django.utils.translation`. That seems like a far more useful way of handling this.

**Comment by MrTango** [comment]
What about:
import pdb; pdb.set_trace( )  # noqa

This also not works and is a verry usefull pattern.
I know that the pdb has to be removed before commiting but for that i use pre commit hook.
And if i decide to use noqa for a statement, why should some one else decide to let this not work?

**Comment by sigmavirus24** [comment]
> And if i decide to use noqa for a statement, why should some one else decide to let this not work?

Because code wins. The authors of pep8 decided to only allow `# noqa` for controversial rules (or rules that PEP-0008 has changed over the years), not for every rule.

**Comment by amigrave** [comment]
Ok, then where can one fill the controversial form for a specific rule ? :-)

**Comment by sigmavirus24** [comment]
> Ok, then where can one fill the controversial form for a specific rule ? :-)

There isn't one. Flake8 3.0 is in the works and will support people using `# noqa` for all errors/warnings though.

**Comment by amigrave** [comment]
Excellent news! Thanks!
