### ISSUE TITLE
StyleGuide config_file parameter is passed in via main, but is ignored by StyleGuide

### ISSUE THREAD

**Issue by streeter** [jcrocholl/pep8#380]
The `config_file` parameter to `StyleGuide` was [removed in 1.6](https://github.com/jcrocholl/pep8/compare/1.5.7...1.6.1#diff-429d64b260de27fe3688921a1592b3f6L1622). However, the value is [still passed in to `_main()`](https://github.com/jcrocholl/pep8/blob/d2ffc129ecb07a6ddba81f0770910cd27b563411/pep8.py#L2094).

In addition, the `config_file` removal isn't mentioned in the [1.6 changelog](https://github.com/jcrocholl/pep8/blob/d2ffc129ecb07a6ddba81f0770910cd27b563411/CHANGES.txt#L25-L78). Because of this, callers can no longer specify which config file to use.

**Comment by IanLee1521** [comment]
Pushed f254233 too fast.. This is resolved in 3bbaa23. It also should fix the regression detailed https://github.com/jcrocholl/pep8/issues/368#issuecomment-74289662 / https://gitlab.com/pycqa/flake8/issues/33
