### ISSUE TITLE
Missing operator detection

### ISSUE THREAD

**Issue by KangOl** [jcrocholl/pep8#382]
the following invalid snippets does not trigger any errors (not even `E211`)

```python
'%s' (42,)
```
```python
'%(a)s' {'a': 42}
```
```python
'%s' 42
```
```python
42 42
```

**Comment by myint** [comment]
I think the right tool for the job in this case would be `pyflakes` (or `flake8`).

**Comment by IanLee1521** [comment]
Correct, these aren't style violations, they are actually SyntaxErrors (well, technically `'%s' (42,)` is a TypeError ;) )
