### ISSUE TITLE
'Ignore' configuration property is only taking the first value

### ISSUE THREAD

**Issue by jelpern** [jcrocholl/pep8#392]
I am running `pep8` on the following code, in a file called `main.py`:

```python
class Task(ndb.Model):

    index = ndb.IntegerProperty(required = True)
    description = ndb.TextProperty(required=True) 
   
```

When  ~/.config/pep8 file looks like this:

`[pep8]`
`ignore = W291, E251`

running `$ pep8 main.py` gives the following output:

`main.py:49:41: E251 unexpected spaces around keyword / parameter equals`
`main.py:49:43: E251 unexpected spaces around keyword / parameter equals`
`main.py:51:1: W293 blank line contains whitespace`

However when I swap the order of the error codes (`ignore = E251, W291`) and run the same command on the same file, I get:

`main.py:50:50: W291 trailing whitespace`
`main.py:51:1: W293 blank line contains whitespace`

It's maddening. Am I doing something wrong, or is this a bug?

I'm having the same problem with Python linting in Sublime Text 3, which is defined by the `ignore` parameter in the user-defined *SublimeLinter.sublime-settings*; not sure if that could be related (I'm following the instructions in https://realpython.com/blog/python/setting-up-sublime-text-3-for-full-stack-python-development/).

Thanks!

**Comment by jelpern** [comment]
I figured this out. The issue was the space between the error codes. Thanks.

**Comment by sigmavirus24** [comment]
This should be fixed by @doismellburning's recent PR. So when we get a release out, you can use spaces, or not. :tada:
