### ISSUE TITLE
ignore rule in configuration  example is misleading. (what is E41?)

### ISSUE THREAD

**Issue by JalapenoGremlin** [jcrocholl/pep8#401]
What does ignoring 

     [pep8]
      ignore = E226,E302,E41
      max-line-length = 160

What does ``ignore = E41`` actually ignore?

Is that a typo?

**Comment by IanLee1521** [comment]
That ignores all E41* codes, it's not a typo. That said, we could probably make that clearer in the documentation.

**Comment by IanLee1521** [comment]
This is not an error, it means that all error codes that match ``E41*``will be ignored.

That said, this is something I can clarify in the documentation.

**Comment by JalapenoGremlin** [comment]
Okay. So it will ignore E41, E410-E419, E4100-E4199, etc. 
Which means it will not ignore anything at this time since there is no E41* error codes (or at least no documented E41* errors) at this time. 
Thanks.

**Comment by sigmavirus24** [comment]
@JalapenoGremlin can you close this?
