### ISSUE TITLE
Test for mixed and explicitly specified linefeeds

### ISSUE THREAD

**Issue by techtonik** [jcrocholl/pep8#405]
Is it possible to implement in pep8 a forced check for mixed linefeeds in .py file and optional check for specific linefeed style (LF) of the project?

**Comment by sigmavirus24** [comment]
This doesn't belong in pep8 if I remember the document correctly. You can write a Flake8 extension for this though
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sigmavirus24** [comment]
And double checking now that I'm at a computer, [PEP 8](https://www.python.org/dev/peps/pep-0008/) has no mention of new-lines - in other words, it doesn't belong here. You're more then welcome to write a [Flake8 extension](https://flake8.readthedocs.org/en/2.4.0/extensions.html).

**Comment by techtonik** [comment]
@sigmavirus24 I asked at https://mail.python.org/pipermail/code-quality/2015-June/thread.html but my message still didn't pass moderation. I suspect that moderators are far away or turned to stone.

**Comment by techtonik** [comment]
`pylint` was able to run the check. Now trying to figure out how to make it run over all Python files recursively without resorting to Unix utils. Anyway, this can be closed. Thanks!
